include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_expression_function_bodies: true
    directives_ordering: true
